"""ensure cases.id identity

Revision ID: 20260114_000003
Revises: 20260114_000002
Create Date: 2026-01-14
"""

from alembic import op


revision = "20260114_000003"
down_revision = "20260114_000002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        DO $$
        BEGIN
          IF NOT EXISTS (
            SELECT 1
            FROM information_schema.columns
            WHERE table_schema = 'public'
              AND table_name = 'cases'
              AND column_name = 'id'
              AND (is_identity = 'YES' OR column_default IS NOT NULL)
          ) THEN
            ALTER TABLE public.cases ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
          END IF;
        END $$;
        """
    )


def downgrade() -> None:
    op.execute(
        """
        DO $$
        BEGIN
          BEGIN
            ALTER TABLE public.cases ALTER COLUMN id DROP IDENTITY IF EXISTS;
          EXCEPTION
            WHEN undefined_object THEN
              NULL;
          END;
        END $$;
        """
    )
